[package]
name = "clustering"
version = "0.1.0"
edition = "2021"

[dependencies]
linfa = "0.7.1"
linfa-clustering = "0.7.1"
linfa-datasets = { version = "0.7.1", features = ["iris"] }
ndarray = "0.15.6"
plotters = "0.3.7"
rand = "0.8.5"
