[package]
name = "linear_classification"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
linfa = "0.7.1"
plotters = "0.3.7"
ndarray = "0.15.6"
linfa-logistic = "0.7.1"
linfa-datasets = { version = "0.7.1", features = ["iris"] }
rand = "0.8.5"
